### ISSUE TITLE
Dataset issue

### ISSUE THREAD

**Issue by KomalKrishM** [wenqihuang/LS-Net-Dynamic-MRI#1]
Hello sir, I am getting errors in generating the tfrecord files. please provide the dataset files used in the code.

**Comment by rui-919** [comment]
Hello wenqi, I get troubles in the dataset section, could you send me the dataset if  you don't mind. My email address is rui919@nefu.edu.cn

**Comment by wenqihuang** [comment]
Hello everyone! Thank you for your interest and sorry for the late reply! I'm sorry to say that providing the data is not possible due to the privacy regulations. But I already added a simple tutorial for creating dataset for L+S-Net. Please check it [here](https://github.com/wenqihuang/LS-Net-Dynamic-MRI/blob/main/create_dummy_data/create_dummy_data.ipynb). You can easily build your dataset with this demo ;) Hope you guys find it useful!
