### ISSUE TITLE
Difference in Low-Rank Layer From the Paper

### ISSUE THREAD

**Issue by JLiu-Edinburgh** [wenqihuang/LS-Net-Dynamic-MRI#4]
Hi,

Thanks for the code. However, the implementation of the low-rank layer seems to take as input Mpre, which shows to be subtracted by S_k in the paper. Could you kindly identify which one is correct, or they make no obvious difference?

Thanks a lot!

**Comment by wenqihuang** [comment]
Hi,

Thanks for spotting this difference! The exact implementation should be Mpre - Spre as shown in the paper. However, you can also use Mpre instead. From a intuative aspect, the SVT is so strong that it will remove almost all the dynamic componet and the artifacts caused by undersampling. Therefore it will not be a big differnce if you involve the S_k or not. Hope this answers your question :)

Best,
Wenqi
