### ISSUE TITLE
If condition while initializing gamma for the dc layer

### ISSUE THREAD

**Issue by Simonodyheit** [wenqihuang/LS-Net-Dynamic-MRI#9]
hi, I am wondering why you have the flag `is_last` for the network layers, such that the gamma for DC is conditional.
That is, see [link](https://github.com/wenqihuang/LS-Net-Dynamic-MRI/blob/d0694bd6aca2d8a7784b494dc9ef6bab46add53e/model.py#L81`): 
```python
self.is_last = is_last
    self.gamma = tf.Variable(tf.constant(1, dtype=tf.float32), trainable=True)
```
Interestingly enough, when I discard the condition and make the `self.gamma` universe for all layers,
```python
# self.is_last = is_last
self.gamma = tf.Variable(tf.constant(1, dtype=tf.float32), trainable=True)
```
 the program throws a warning that I can not figure out the reason.
```txt
WARNING:tensorflow:Gradients do not exist for variables ['LplusS_Net/gamma:0'] when minimizing the loss.
```
FYI, I have assigned a name during `self.gamma` initialization so I can pin the warning source.

Do you happen to have any idea of why this occurs?

**Comment by wenqihuang** [comment]
Hi Simonodyheit,

during training we disable the last data consistency and feed directly the CNN output for loss calculation so that without the 'last help' of DC, the network can learn better. That also means the last gamma will never join in the forward path, thus no gradient exists for it.In our implementation we simply skip the initialization of the last gamma to avid the warning you came across. Hope this explanation is helpful :)

Best,
Wenqi
